// Shows a page's tags as capsule links right beneath the article title.
//
// The tags come from `file.data.frontmatter.tags`, which
// `@quartz-community/note-properties` fills in from the frontmatter `tags` /
// `tag` field, slugifying and de-duplicating each entry. That plugin stays
// enabled as the frontmatter parser; its own properties table is hidden by
// `hidePropertiesView: true`, so this component is what surfaces the tags.
//
// Every pill links to the matching `tags/<tag>` page generated by
// `@quartz-community/tag-page`. The component itself lives in
// `components/index.js`; this module only carries the manifest the loader reads
// to find it.

export const manifest = {
  name: "tag-pills",
  displayName: "Tag Pills",
  description: "Render a page's tags as capsule links beneath the article title.",
  version: "1.0.0",
  category: "component",
  quartzVersion: ">=5.0.0",
  components: {
    TagPills: {
      displayName: "Tag Pills",
      defaultPosition: "beforeBody",
      defaultPriority: 15,
    },
  },
}
